// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drones.sql

package db

import (
	"context"
)

const countDronesByStatus = `-- name: CountDronesByStatus :many
SELECT status, count(*) AS total
FROM drones
GROUP BY status
`

type CountDronesByStatusRow struct {
	Status DroneStatus `json:"status"`
	Total  int64       `json:"total"`
}

func (q *Queries) CountDronesByStatus(ctx context.Context) ([]CountDronesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countDronesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDronesByStatusRow{}
	for rows.Next() {
		var i CountDronesByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDrone = `-- name: GetDrone :one
SELECT id, name, status, battery, lat, lng, altitude, mission_id, created_at, updated_at
FROM drones
WHERE id = $1
`

func (q *Queries) GetDrone(ctx context.Context, id string) (Drone, error) {
	row := q.db.QueryRow(ctx, getDrone, id)
	var i Drone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Battery,
		&i.Lat,
		&i.Lng,
		&i.Altitude,
		&i.MissionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTelemetryEvent = `-- name: InsertTelemetryEvent :one
INSERT INTO telemetry_events (drone_id, lat, lng, altitude, battery)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, drone_id, lat, lng, altitude, battery, recorded_at
`

type InsertTelemetryEventParams struct {
	DroneID  string  `json:"drone_id"`
	Lat      float64 `json:"lat"`
	Lng      float64 `json:"lng"`
	Altitude float64 `json:"altitude"`
	Battery  int32   `json:"battery"`
}

func (q *Queries) InsertTelemetryEvent(ctx context.Context, arg InsertTelemetryEventParams) (TelemetryEvent, error) {
	row := q.db.QueryRow(ctx, insertTelemetryEvent,
		arg.DroneID,
		arg.Lat,
		arg.Lng,
		arg.Altitude,
		arg.Battery,
	)
	var i TelemetryEvent
	err := row.Scan(
		&i.ID,
		&i.DroneID,
		&i.Lat,
		&i.Lng,
		&i.Altitude,
		&i.Battery,
		&i.RecordedAt,
	)
	return i, err
}

const listDrones = `-- name: ListDrones :many
SELECT id, name, status, battery, lat, lng, altitude, mission_id, created_at, updated_at
FROM drones
ORDER BY id
`

func (q *Queries) ListDrones(ctx context.Context) ([]Drone, error) {
	rows, err := q.db.Query(ctx, listDrones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Drone{}
	for rows.Next() {
		var i Drone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Battery,
			&i.Lat,
			&i.Lng,
			&i.Altitude,
			&i.MissionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverDrone = `-- name: RecoverDrone :one
UPDATE drones
SET status = 'idle',
    updated_at = now()
WHERE id = $1
RETURNING id, name, status, battery, lat, lng, altitude, mission_id, created_at, updated_at
`

func (q *Queries) RecoverDrone(ctx context.Context, id string) (Drone, error) {
	row := q.db.QueryRow(ctx, recoverDrone, id)
	var i Drone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Battery,
		&i.Lat,
		&i.Lng,
		&i.Altitude,
		&i.MissionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const simulateDroneFault = `-- name: SimulateDroneFault :one
UPDATE drones
SET status = 'fault',
    battery = 10,
    updated_at = now()
WHERE id = $1
RETURNING id, name, status, battery, lat, lng, altitude, mission_id, created_at, updated_at
`

func (q *Queries) SimulateDroneFault(ctx context.Context, id string) (Drone, error) {
	row := q.db.QueryRow(ctx, simulateDroneFault, id)
	var i Drone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Battery,
		&i.Lat,
		&i.Lng,
		&i.Altitude,
		&i.MissionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDroneTelemetry = `-- name: UpdateDroneTelemetry :one
UPDATE drones
SET lat = $2,
    lng = $3,
    altitude = $4,
    battery = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, status, battery, lat, lng, altitude, mission_id, created_at, updated_at
`

type UpdateDroneTelemetryParams struct {
	ID       string  `json:"id"`
	Lat      float64 `json:"lat"`
	Lng      float64 `json:"lng"`
	Altitude float64 `json:"altitude"`
	Battery  int32   `json:"battery"`
}

func (q *Queries) UpdateDroneTelemetry(ctx context.Context, arg UpdateDroneTelemetryParams) (Drone, error) {
	row := q.db.QueryRow(ctx, updateDroneTelemetry,
		arg.ID,
		arg.Lat,
		arg.Lng,
		arg.Altitude,
		arg.Battery,
	)
	var i Drone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Battery,
		&i.Lat,
		&i.Lng,
		&i.Altitude,
		&i.MissionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
