// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: missions.sql

package db

import (
	"context"
)

const getMission = `-- name: GetMission :one
SELECT id, drone_id, status, started_at, completed_at, created_at, updated_at
FROM missions
WHERE id = $1
`

func (q *Queries) GetMission(ctx context.Context, id string) (Mission, error) {
	row := q.db.QueryRow(ctx, getMission, id)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.DroneID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMissionWaypoints = `-- name: ListMissionWaypoints :many
SELECT mission_id, sequence, lat, lng, alt
FROM mission_waypoints
WHERE mission_id = $1
ORDER BY sequence
`

func (q *Queries) ListMissionWaypoints(ctx context.Context, missionID string) ([]MissionWaypoint, error) {
	rows, err := q.db.Query(ctx, listMissionWaypoints, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MissionWaypoint{}
	for rows.Next() {
		var i MissionWaypoint
		if err := rows.Scan(
			&i.MissionID,
			&i.Sequence,
			&i.Lat,
			&i.Lng,
			&i.Alt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissions = `-- name: ListMissions :many
SELECT id, drone_id, status, started_at, completed_at, created_at, updated_at
FROM missions
ORDER BY id
`

func (q *Queries) ListMissions(ctx context.Context) ([]Mission, error) {
	rows, err := q.db.Query(ctx, listMissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mission{}
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.DroneID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
