// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountDronesByStatus(ctx context.Context) ([]CountDronesByStatusRow, error)
	GetDrone(ctx context.Context, id string) (Drone, error)
	GetMission(ctx context.Context, id string) (Mission, error)
	InsertTelemetryEvent(ctx context.Context, arg InsertTelemetryEventParams) (TelemetryEvent, error)
	ListDrones(ctx context.Context) ([]Drone, error)
	ListMissionWaypoints(ctx context.Context, missionID string) ([]MissionWaypoint, error)
	ListMissions(ctx context.Context) ([]Mission, error)
	RecoverDrone(ctx context.Context, id string) (Drone, error)
	SimulateDroneFault(ctx context.Context, id string) (Drone, error)
	UpdateDroneTelemetry(ctx context.Context, arg UpdateDroneTelemetryParams) (Drone, error)
}

var _ Querier = (*Queries)(nil)
